### PR TITLE
Need to build the binary.

### PR DESCRIPTION
**Pull request by ranforce**
Ref to https://github.com/asticode/go-astilectron-bundler#build-the-binary

Thanks

### CODE REVIEW

**Comment by asticode** [comment]
@ranforce the binary should be built when executing `go get -u`. Isn't that the case in your case? Which go version are you using?

**Comment by ranforce** [comment]
My case is on win7. Os System Windows 7.

**Comment by ranforce** [comment]
go version go1.11 windows/amd64

**Comment by asticode** [comment]
Merged.

Cheers

**Pull request merged**
